name: Auto release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Dist
        run: yarn install && yarn build
      - name: Upload process map file to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: arkadia-extension.zip
          asset_name: arkadia-extension.zip
          tag: ${{ github.ref }}
          overwrite: true
